server:
  port: 8080
spring:
  profiles:
    active: ${JAVA_ENV:dev}
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:sql/create.sql
  #?????, ??????(???????????????404)
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #?????????????????
  resources:
    add-mappings: true

